on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests.
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_TEST_UC_HOSTS: ${{ secrets.QINIU_TEST_UC_HOSTS }}
          QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
          QINIU_KODO_TEST: "on"
        run: go run operation/internal/x/gotest.v1/main.go 5 ./operation
