on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests.
        env:
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_TEST_UP_HOSTS: ${{ secrets.QINIU_TEST_UP_HOSTS }}
          QINIU_TEST_RSF_HOSTS: ${{ secrets.QINIU_TEST_RSF_HOSTS }}
          QINIU_TEST_RS_HOSTS: ${{ secrets.QINIU_TEST_RS_HOSTS }}
          QINIU_TEST_API_SERVER_HOSTS: ${{ secrets.QINIU_TEST_API_SERVER_HOSTS }}
          QINIU_TEST_IO_HOSTS: ${{ secrets.QINIU_TEST_IO_HOSTS }}
          QINIU_TEST_UC_HOSTS: ${{ secrets.QINIU_TEST_UC_HOSTS }}
          QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
        run: go test ./...
